name: Build Docker images

on:
  push:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mautic-version: [4.4.0, 4.3.1, 4.3.0, 4.2.2, 4.2.1]
        image: [apache, fpm]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: download mautic
        run: |
          wget -O mautic.zip https://github.com/mautic/mautic/releases/download/${{ matrix.mautic-version }}/${{ matrix.mautic-version}}.zip
          echo MAUTIC_SHA1="$(sha1sum mautic.zip | sed -r 's/ .*//')" >> $GITHUB_ENV
      - name: echo mautic version and sha1sum 
        run: echo ${{ matrix.mautic-version }} - ${{ env.MAUTIC_SHA1 }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-${{ matrix.image }}-mautic4-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-${{ matrix.image }}-mautic4-buildx-
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Build ${{ matrix.image }} image
        uses: docker/build-push-action@v2
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: ${{ matrix.image }}/Dockerfile
          build-args: |
            MAUTIC_VERSION=${{ matrix.mautic-version }}
            MAUTIC_SHA1=${{ env.MAUTIC_SHA1 }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ivanmonteiro/mautic:v${{ matrix.mautic-version }}-${{ matrix.image }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new,mode=max
        # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache