name: Build Docker images

on:
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        mautic-version: [4.4.0]
        image: [apache, fpm]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: copy common files
        run: cp -r common/* ${{ matrix.image }}
      - name: download mautic
        run: wget -O mautic.zip https://github.com/mautic/mautic/releases/download/${{ matrix.mautic-version }}/${{ matrix.mautic-version}}.zip
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build ${{ matrix.image }} image
        uses: docker/build-push-action@v2
        with:
          context: ${{ matrix.image }}
          build-args: MAUTIC_VERSION=${{ steps.tag.outputs.TAG }}
          push: false
          tags: mautic/docker-${{ matrix.image }}:latest
